### ISSUE TITLE
大佬，这个报错是什么设置不对么？

### ISSUE THREAD

**Issue by hb255** [williamnie/91pron-#2]
`C:\Program Files\nodejs\91pron>node app.js
running
C:\Program Files\nodejs\91pron\node_modules\cheerio\lib\parse.js:69
    var oldParent = node.parent || node.root,
                        ^

TypeError: Cannot read property 'parent' of undefined
    at Function.exports.update (C:\Program Files\nodejs\91pron\node_modules\chee
rio\lib\parse.js:69:25)
    at module.exports (C:\Program Files\nodejs\91pron\node_modules\cheerio\lib\p
arse.js:19:11)
    at Function.exports.load (C:\Program Files\nodejs\91pron\node_modules\cheeri
o\lib\static.js:27:14)
    at Request._callback (C:\Program Files\nodejs\91pron\app.js:17:25)
    at self.callback (C:\Program Files\nodejs\91pron\node_modules\request\reques
t.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (C:\Program Files\nodejs\91pron\node_modules\reque
st\request.js:884:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)

C:\Program Files\nodejs\91pron>`

nodejs版本 v6.11.2

顺便问一下，这个是什么原理？ O(∩_∩)O

**Comment by williamnie** [comment]
这个报错,应该是你的网址不对,或者他的页面元素错了,找不到对应的id,这个原理很简单,其实就是,请求页面,然后将返回的页面中的视频地址取出来,直接访问就可以了,request负责请求,cheerio负责解析页面结构(jquery语法)

**Comment by williamnie** [comment]
fixed
